version: '3'

services:
  rails:
    container_name: rails
    build: .
    ports:
      - '3000:3000'
      - '3035:3035'
      - '587:587'
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=3306"
      - "DATABASE_USER=root"
      - "DATABASE_PASSWORD=password"
    links:
      - db
    volumes:
      - '.:/app'
      - 'bundle:/usr/local/bundle'
    stdin_open: true
    tty: true

  db:
    container_name: db
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  bundle:
  mysql-volume:
